In [2]:

import numpy as np

In [1]:
import matplotlib.pyplot as plt

In [3]:
import pandas as pd

In [4]:
path = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [5]:
headernames = ['sepal-length', 'sepal-width','petal-width','Class']

In [6]:
dataset = pd.read_csv(path, names = headernames)

In [7]:
dataset.head()

sepal-length  sepal-width  petal-width        Class
5.1           3.5          1.4          0.2  Iris-setosa
4.9           3.0          1.4          0.2  Iris-setosa
4.7           3.2          1.3          0.2  Iris-setosa
4.6           3.1          1.5          0.2  Iris-setosa
5.0           3.6          1.4          0.2  Iris-setosa

In [32]:
x = dataset.iloc[:, :-1].values

In [33]:
x

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.1, 1.5, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [37]:
y = dataset.iloc[:, -1].values

In [40]:
y[0]

'Iris-setosa'

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size = 0.40)

In [43]:
y_train[1]

'Iris-virginica'

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [46]:
scaler.fit(x_train)

StandardScaler()

In [47]:
x_train = scaler.transform(x_train)

In [48]:
x_test = scaler.transform(x_test)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
classifier = KNeighborsClassifier(n_neighbors = 8)

In [51]:
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [53]:
y_pred = classifier.predict(x_test)

In [54]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [55]:
result = confusion_matrix(y_test, y_pred)

In [56]:
print ("Confusion Matrix:")

Confusion Matrix:


In [57]:
print(result)

[[16  0  0]
 [ 0 20  0]
 [ 0  5 19]]


In [58]:
result1 = classification_report(y_test, y_pred)

In [59]:
print("Classification Report:",)

Classification Report:


In [60]:
print(result1)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.80      1.00      0.89        20
 Iris-virginica       1.00      0.79      0.88        24

       accuracy                           0.92        60
      macro avg       0.93      0.93      0.92        60
   weighted avg       0.93      0.92      0.92        60



In [61]:
result2 = accuracy_score(y_test,y_pred)

In [62]:
print("Accuracy:",result2)

Accuracy: 0.9166666666666666
