In [1]:
import numpy as np

In [2]:
from sklearn import linear_model

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))

In [4]:
y = np.array([5, 20, 14, 32, 22, 38])

In [5]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [6]:
print(y)

[ 5 20 14 32 22 38]


In [10]:
model = linear_model.LinearRegression()

In [11]:
model.fit(x, y)

LinearRegression()

In [14]:
model =  linear_model.LinearRegression().fit(x, y)

In [15]:
r_sq = model.score(x, y)

In [ ]:
print('coefficient of determination:', r_sq)

In [16]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [17]:
print('slope:', model.coef_)

slope: [0.54]


In [18]:
new_model = linear_model.LinearRegression().fit(x, y.reshape((-1, 1)))

In [19]:
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


In [20]:
print('slope:', new_model.coef_)

slope: [[0.54]]


In [21]:
y_pred = model.predict(x)

In [22]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [23]:
y_pred = model.intercept_ + model.coef_ * x

In [24]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [26]:
x_new = np.arange(5).reshape((-1, 1))

In [27]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [28]:
y_new = model.predict(x_new)

In [29]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
