In [2]:
import numpy as np

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55,34], [60,35]]


In [5]:
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [6]:
x, y = np.array(x), np.array(y)

In [7]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [8]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [9]:
model = LinearRegression().fit(x, y)

In [10]:
r_sq = model.score(x, y)

In [11]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8615939258756776


In [13]:
print('intercept:', model.intercept_)

intercept: 5.52257927519819


In [14]:
print('slope:', model.coef_)

slope: [0.44706965 0.25502548]


In [15]:
y_pred = model.predict(x)

In [16]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [17]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)

In [18]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [19]:
x_new = np.arange(10).reshape((-1, 2))

In [20]:
print(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
y_new = model.predict(x_new)

In [22]:
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
