In [1]:
import numpy as numpy

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
import numpy as np

In [14]:
a = np.array([2, 3, 4])

In [15]:
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b = np.array([1.2, 3.5, 5.1])

In [18]:
b.dtype

dtype('float64')

In [19]:
a = np.array([1, 2, 3, 4])

In [20]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [21]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [23]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [28]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [29]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
from numpy import pi

In [31]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
x = np.linspace(0, 2 * pi,100)

In [33]:
f = np.sin(x)

In [34]:
a = np.arange(6)

In [35]:
print(a)

[0 1 2 3 4 5]


In [36]:
b = np.arange(12).reshape(4, 3)

In [37]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
c = np.arange(24).reshape(2, 3, 4)

In [39]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [41]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [42]:
np.set_printoptions(threshold=sys.maxsize)

In [43]:
a = np.array([20, 30, 40, 50])

In [44]:
b = np.arange(4)

In [45]:
b

array([0, 1, 2, 3])

In [46]:
c = a - b

In [47]:
c

array([20, 29, 38, 47])

In [48]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [49]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [50]:
a < 35

array([ True,  True, False, False])

In [51]:
A = np.array([[1, 1],
              [0, 1]])

In [52]:
B = np.array([[2,0],
              [3, 4]])

In [53]:
A * B

array([[2, 0],
       [0, 4]])

In [54]:
A @ B

array([[5, 4],
       [3, 4]])

In [55]:
A.dot(B)

array([[5, 4],
       [3, 4]])