In [1]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\Roja Achary\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Roja Achary\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
clf = RandomForestClassifier(random_state=0)

In [3]:
X = [[ 1, 2, 3],  
     [11, 12, 13]]

In [4]:
y = [0, 1]

In [5]:
clf.fit(X, y)

C:\Users\Roja Achary\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [9]:
clf.predict(X) 

array([0, 1])

In [10]:
clf.predict([[4, 5, 6], [14, 15, 16]])

array([0, 1])

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
X = [[0, 15],
     [1, -10]]
    

In [13]:
StandardScaler().fit(X).transform(X)

array([[-1.,  1.],
       [ 1., -1.]])

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.pipeline import make_pipeline

In [17]:
from sklearn.datasets import load_iris

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
pipe = make_pipeline(StandardScaler(),LogisticRegression())

In [21]:
X, y = load_iris(return_X_y=True)

In [22]:
X_train, X_test, Y_train, y_test = train_test_split(X, y, random_state=0)

In [23]:
pipe.fit(X_train, Y_train)

C:\Users\Roja Achary\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Roja Achary\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [24]:
accuracy_score(pipe.predict(X_test), y_test)

0.8157894736842105

In [26]:
from sklearn.datasets import make_regression


In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
from sklearn.model_selection import cross_validate

In [29]:
X, y = make_regression(n_samples=1000, random_state=0)

In [31]:
lr = LinearRegression()


In [32]:
result = cross_validate(lr, X, y)

C:\Users\Roja Achary\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [33]:
result['test_score']

array([1., 1., 1.])

In [34]:
from sklearn.datasets import fetch_california_housing

In [35]:
from sklearn.ensemble import RandomForestRegressor

In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
from scipy.stats import randint

In [40]:
X, y = fetch_california_housing(return_X_y=True)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [42]:
param_distributions = {'n_estimators': randint(1, 5),'max_depth': randint(5, 10)}

In [43]:
search = RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0),n_iter=5,
param_distributions=param_distributions,random_state=0)

In [44]:
search.fit(X_train, y_train)
RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0), n_iter=5, param_distributions={'max_depth':...,'n_estimators': ...}, random_state=0)

C:\Users\Roja Achary\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


RandomizedSearchCV(cv='warn', error_score='raise-deprecating',
                   estimator=RandomForestRegressor(bootstrap=True,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features='auto',
                                                   max_leaf_nodes=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   n_estimators='warn',
                                                   n_jobs=None, oob_score=False,
                                                   random_st

In [46]:
search.best_params_

{'max_depth': 9, 'n_estimators': 4}

In [47]:
search.score(X_test, y_test)

0.7349601117850644